name: mighty_ebook
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  #BASE
  cupertino_icons: ^1.0.8
  google_fonts: ^6.3.1
  intl: ^0.20.2

  #UI
  cached_network_image: ^3.4.1
  flutter_staggered_animations: ^1.1.1
  flutter_vector_icons: ^2.0.0

  # Firebase
  firebase_analytics: ^12.0.2
  firebase_core: ^4.1.1
  firebase_crashlytics: ^5.0.2
  firebase_core_platform_interface: ^6.0.1

  #STATE MANAGEMENT
  mobx: ^2.5.0
  flutter_mobx: ^2.3.0

  #CONNECTIVITY
  http: ^1.5.0
  connectivity_plus: ^7.0.0
  package_info_plus: ^8.2.1
  share_plus: ^12.0.0
  store_redirect: ^2.0.4

  # WEB TOOLS
  flutter_inappwebview: ^6.1.5

  # ADS
  google_mobile_ads: ^6.0.0
  in_app_purchase: ^3.0.0
  facebook_audience_network: ^1.0.1

  # PUSH NOTIFICATION
  onesignal_flutter: ^5.3.4

  # LAUNCH URL
  url_launcher: ^6.3.2

  #Database
  shared_preferences: ^2.5.3

  fluttertoast: ^9.0.0
  html: ^0.15.6
  carousel_slider: ^5.1.1
  flutter_staggered_grid_view: ^0.7.0

  # Image Picker for Avatar
  image_picker: ^1.0.7

  #PDF
  syncfusion_flutter_pdfviewer: ^31.1.21

  #Localization
  flutter_localizations:
    sdk: flutter
  device_info_plus: ^12.3.0
  dio: ^5.9.0
  path_provider: ^2.1.5
  flutter_secure_storage: ^10.0.0
  encrypt: ^5.0.3
  permission_handler: ^12.0.1



dev_dependencies:
  flutter_test:
    sdk: flutter

  mobx_codegen: ^2.7.0
  build_runner: ^2.8.0
  #flutter packages pub run build_runner build --delete-conflicting-outputs

  flutter_lints: ^6.0.0

dependency_overrides:
  connectivity_plus: 5.0.2
  intl: ^0.19.0


flutter:
  uses-material-design: true
  assets:
    - asset/
    - asset/flag/
